version: '2'
services:
  postgresql:
    container_name: postgresql
    image: postgres:11-alpine
    environment:
      - POSTGRES_DB=alianza
      - POSTGRES_USER=alianza
      - POSTGRES_PASSWORD=alianza
    ports:
      - 5555:5432
